/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_spectrogramengine_free: (a: number, b: number) => void;
export const __wbg_waveformengine_free: (a: number, b: number) => void;
export const compute_wave_peaks: (a: number, b: number, c: number) => [number, number];
export const find_global_max: (a: number, b: number) => number;
export const spectrogramengine_clear_filter_bank: (a: number) => void;
export const spectrogramengine_compute_spectrogram: (a: number, b: number, c: number, d: number) => [number, number];
export const spectrogramengine_compute_spectrogram_image: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const spectrogramengine_compute_spectrogram_u8: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const spectrogramengine_get_fft_size: (a: number) => number;
export const spectrogramengine_get_freq_bins: (a: number) => number;
export const spectrogramengine_get_global_max: (a: number) => number;
export const spectrogramengine_get_num_filters: (a: number) => number;
export const spectrogramengine_get_peak_magnitudes: (a: number, b: number) => [number, number];
export const spectrogramengine_get_peaks: (a: number, b: number) => [number, number];
export const spectrogramengine_get_window_values: (a: number) => [number, number];
export const spectrogramengine_load_filter_bank: (a: number, b: number, c: number, d: number) => void;
export const spectrogramengine_new: (a: number, b: number, c: number, d: number) => number;
export const spectrogramengine_set_color_map: (a: number, b: number, c: number) => void;
export const spectrogramengine_set_spectrum_config: (a: number, b: number, c: number, d: number, e: number) => void;
export const waveformengine_clear: (a: number) => void;
export const waveformengine_get_channel_length: (a: number, b: number) => number;
export const waveformengine_get_num_channels: (a: number) => number;
export const waveformengine_get_peaks_in_range: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const waveformengine_load_channel: (a: number, b: number, c: number, d: number) => void;
export const waveformengine_new: () => number;
export const waveformengine_resize: (a: number, b: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
